---
- name: robertdebock.bootstrap
  version: 4.2.0
- name: robertdebock.core_dependencies
  version: 1.4.0
- name: robertdebock.java
  version: 2.5.0
- name: robertdebock.service
  version: 2.6.0
- name: robertdebock.tomcat
  version: 4.5.0
